---
- name: "Install Composer into the current directory."
  when: 
    ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
    or
    ansible_distribution == 'Debian' and (ansible_distribution_major_version == "7" or ansible_distribution_major_version >= "8")
  shell: >
    curl -sS https://getcomposer.org/installer | php
    creates={{ composer_path }}

- name: "Move Composer into globally-accessible location."
  when: 
    ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'
    or
    ansible_distribution == 'Debian' and (ansible_distribution_major_version == "7" or ansible_distribution_major_version >= "8")
  shell: >
    mv composer.phar {{ composer_path }}
    creates={{ composer_path }}

- name: "Creates composer config directory"
  file: 
    path=/root/.composer 
    state=directory

- name: "Configure github oauth token"
  template:
    src: "auth.json.j2"
    dest: "~/.composer/auth.json"

 